### PR TITLE
Require AppropriateImages in `vimeoThumbnail` prop in `RelatedPage`

### PR DESCRIPTION
**Pull request by katydecorah**
*This PR merges into #393* 

This PR makes `vimeoThumbnail` require AppropriateImages rather than a string. This will help improve performance of these thumbnail images by making sure they are compressed.

## How to test

- [x] View the /RelatedPage test case (`npm start`) and make sure image loads
- [x] View /accounts/guides/settings/#setting-up-saml-sso-for-your-mapbox-account on staging and make sure image loads

Note:
- I needed to add video-thumb generated images to the the catalog page and test case files to get the path to work correctly in path environments. A little annoying, but I couldn't find a better workaround!

## QA checklist

- [x] No errors logged to console.
- [x] Accessibility score in [Chrome DevTools Audit/Lighthouse](https://developers.google.com/web/tools/lighthouse#devtools) is 100% with Lighthouse version: `#.#.#`.
- [x] Component is accessible at mobile-size viewport.
- [x] Component is accessible at tablet-size viewport.
- [x] Component is accessible at laptop-size viewport.
- [x] Component is accessible at big-monitor-size viewport.
- [x] Create a PR in a site repo, copy the component, and test it. Push to staging and let the reviewer know they can also test the component there.

Open the test cases app locally on:

- [x] Chrome, no errors logged to console.
- [x] Firefox, no errors logged to console.
- [x] Safari, no errors logged to console.
- [x] Edge, no errors logged to console.
- [x] IE11, no errors logged to console.
- [x] Mobile Safari, no errors logged to console.
- [x] Android Chrome, no errors logged to console.

### CODE REVIEW

**Comment by katydecorah** [comment]
@colleenmcginnis This will likely be the last dr-ui PR  for this quest (unless something comes up during rollout)!

**Comment by katydecorah** [comment]
@colleenmcginnis whoops, there may be _one_ more if we decide to drop IE 11 support (to be determined in sync today)!

**Review by colleenmcginnis — APPROVED** [review]
Makes sense to me! It's kind of annoying that we'll need to import the repo-specific `AppropriateImage` component in every md file that uses `RelatedPage` to link to a video, but I can't think of any way to get around that...

**Comment by katydecorah** [comment]
> It's kind of annoying that we'll need to import the repo-specific AppropriateImage component in every md file that uses RelatedPage to link to a video

Yeah, I agree! I think during this work with compression we'll start to find more things that aren't great about rendering images and other assets and I will start to write them down. It's possible that we are out growing the AppropriateImage system, but it's the best method we have right now to make sure images are optimized. I think once we have full compliance, it'll be easier to either find a new system or make updates to the current one!

**Pull request merged**
